config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'facebook#create'

  resources :meals
  resources :ingredients
  resources :users
  resources :recipes do
    resources :images, only: [:show, :new, :destroy, :edit]
    resources :comments
  end

  resources :images
  resources :comments

  resources :recipe_ingredients, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :recipe 
  validates :url, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :recipes

  def to_param
    "#{id}-#{title}"
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  belongs_to :meal
  has_many :images
  has_many :comments
  validates :name, :instructions, presence: true

  def recipe_ingredients_attributes=(recipe_ingredients_attributes)

    recipe_ingredients_attributes.each do |recipe_ingredient_attribute|
      ingredient = Ingredient.find_or_create_by(name: recipe_ingredient_attribute[1]["name"])
      if !ingredient.name.blank?
        self.recipe_ingredients.build(quantity: recipe_ingredient_attribute[1]["quantity"], ingredient_id: ingredient.id)
      end
    end
  end

  def self.by_meal(meal_id)
    where(meal: meal_id)
  end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  def name
    if  Ingredient.find_by(id: ingredient_id)
      ingredient = Ingredient.find_by(id: ingredient_id)
      ingredient.name
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :comments
  has_secure_password
  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
      redirect_to recipe_path(@recipe)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController

  def create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.password_digest = SecureRandom.hex(10)
      u.name = auth['info']['name']
      u.email = auth['info']['email']
    end

    session[:user_id] = @user.id

    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include ApplicationHelper

  def new
    @image = Image.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:image][:recipe_id])
    if current_user == @recipe.user
      @image = Image.new(image_params)
      if @image.save
        redirect_to recipe_path(@recipe)
      else
        render 'new'
      end
    end
  end
 
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    if current_user == @recipe.user
      @image = Image.find(params[:id]).destroy
      redirect_to recipe_path(@recipe)
    end
  end

  def show
    @image = Image.find(params[:recipe_id])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:image][:recipe_id])
    if current_user == @recipe.user
      @image = Image.find(params[:id])
      if @image.update(image_params)
        redirect_to recipe_path(@recipe)
      else
        render 'edit'
      end
    end
  end

  private

  def image_params
    params.require(:image).permit(:url, :caption, :recipe_id)
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    @recipes = Recipe.by_meal(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include ApplicationHelper
  def new
    if logged_in?
      @recipe = Recipe.new
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
    else
      redirect_to root_path
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = session[:user_id]
    if @recipe.save

      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @recipe.comments.build

  end

  def edit
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
      @recipe.recipe_ingredients.build
    else
      redirect_to root_path
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      if @recipe.update(recipe_params)
        redirect_to recipe_path(@recipe)
      else
        render 'edit'
      end
    end
  end

  def index
    @recipes = Recipe.all
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to user_path(current_user)
    else
      redirect_to root_path
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cook_time, :servings, :instructions, :meal_id, recipe_ingredients_attributes: [:name, :quantity])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if User.find_by(email: params[:session][:email])
      @user = User.find_by(email: params[:session][:email])
      return head(:forbidden) unless @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    if logged_in?
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to root_path
    end
  end

  def destroy
    session.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ApplicationHelper

  def home
    if logged_in?
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    session[:user_id]
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.content %>

app/views/comments/_form.html.erb
<%= form_for([@recipe, @recipe.comments.build]) do |f| %>
  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>
    <%= f.submit %>
<% end %>

app/views/images/_form.html.erb
<%= form_for @image do |f| %>

  <%= f.hidden_field :recipe_id %>

  <div class="field_with_errors">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <br />

  <%= f.label :caption %>
  <%= f.text_area :caption %>

  <br />

  <%= f.submit %>
  
<% end %>

app/views/images/edit.html.erb
<% if @image.errors.any? %>

  <div id="error_explanation">

    <h2>
      <%= pluralize(@image.errors.count, "error") %>
      prohibited this image from being edited:
    </h2>

    <ul>
    <% @image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  </div>

<% end %>

<h2>Edit Image</h2>
<%= render partial: "form" %>

app/views/images/new.html.erb
<% if @image.errors.any? %>

  <div id="error_explanation">

    <h2>
      <%= pluralize(@image.errors.count, "error") %>
      prohibited this image from being saved:
    </h2>

    <ul>
    <% @image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  </div>

<% end %>

<h1>Upload an Image</h1>
<%= render partial: "form" %>

app/views/images/show.html.erb
<p><img width="400px" src="<%= @image.url %>"></p>
<p><%= @image.caption %></p>

app/views/meals/index.html.erb
<h1>Browse Recipes</h1>

<ul>
  <% @meals.each do |meal| %>
    <li><%= link_to "#{meal.title}", meal_path(meal) %></li>
  <% end %>
  <li><%= link_to "All", recipes_path %></li>
</ul>

app/views/meals/show.html.erb
<%= link_to "Back", meals_path %>

<h1><%= @meal.title %></h1>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to "#{recipe.name}", recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <div class="field_with_errors">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </div>

  <br />

  <%= f.label :description %>
  <br />
  <%= f.text_area :description %>

  <br />

  <%= f.label :cook_time %>
  <br />
  <%= f.text_field :cook_time %>

  <br />

  <%= f.label :servings %>
  <br />
  <%= f.text_field :servings %>

  <br />

  <br />
  <%= f.fields_for :recipe_ingredients do |rf| %>
    Ingredient:<%= rf.text_field :name %>
    Quantity:<%= rf.text_field :quantity %>
    <br />
  <% end %>

  <br />

  <div class="field_with_errors">
    <%= f.label :instructions %>
    <br />
    <%= f.text_area :instructions %>
  </div>

  <br />
  <%= f.collection_select :meal_id, Meal.all, :id, :title %>
  <br />

  <%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>

  <div id="error_explanation">

    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this recipe from being edited:
    </h2>

    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  </div>

<% end %>

<h2>Edit Recipe</h2>
<%= render partial: "form" %>

app/views/recipes/index.html.erb
<%= link_to "Back", meals_path %>

<h1>Browse Recipes</h1>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to "#{recipe.name}", recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>

  <div id="error_explanation">

    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this recipe from being created:
    </h2>

    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  </div>
  
<% end %>

<h2>Create a New Recipe</h2>
<%= render partial: "form" %>

app/views/recipes/show.html.erb
<%= link_to "Browse Recipes", meals_path %>

<h1><%= @recipe.name %></h1>

<% @recipe.images.each do |image| %>
  <p><a href="<%= recipe_image_path(image, @recipe) %>"><img width="400px" src="<%= image.url %>"></a></p>
  <%= image.caption %>

  <% if current_user == @recipe.user %>
    <%= link_to "Edit Image", edit_recipe_image_path(@recipe, image) %>
    <%= form_tag recipe_image_path(@recipe.id, image.id), method: "delete" %>
      <%= submit_tag "Delete Image" %>
  <% end %>
<% end %>

<% if current_user == @recipe.user %>
  <%= link_to "Add Image", new_recipe_image_path(@recipe) %>
<% end %>

<br />
<br />

<h2>Recipe Author:</h2>
<p><%= @user.name %></p>

<h2>Description:</h2>
<p><%= @recipe.description %></p>

<h2>Cook Time:</h2>
<p><%= @recipe.cook_time %></p>

<h2>Servings:</h2>
<p><%= @recipe.servings %></p>

<h2>Ingredients</h2>
  <ul>
    <% @recipe.ingredients.each do |i| %>
    <% @ri = RecipeIngredient.find_by(recipe_id: @recipe.id, ingredient_id: i.id) %>

      <li><%= i.name %>
        <%= @ri.quantity %>

      <% if current_user == @recipe.user %>

      <%= form_tag recipe_ingredient_path(i.id), method: "delete" do %>
      <%= hidden_field(:recipe, :id) %>
      <%= submit_tag "Delete Ingredient" %></li>

      <% end %>
    <% end %>
    <% end %>
  </ul>


<h2>Cooking Instructions</h2>
<p><%= @recipe.instructions %></p>

<br />
Leave Comment:
<% if current_user %>
<%= render 'comments/form' %>
<% end %>

<h2>Comments</h2>
<%= render @recipe.comments %>

<br />
<br />

<% if current_user == @recipe.user %>
  <%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>
  <br />
  <%= form_tag recipe_path(@recipe.id), method: "delete"  do %>
    <%= submit_tag "Delete Recipe" %>
    <% end %>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>

  <div id="error_explanation">

    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited you from creating an account:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  </div>

<% end %>

<%= form_for @user do |f| %>
  <div class="field_with_errors">
    <p>Name:</p>
    <%= f.text_field :name %>
  </div>

  <div class="field_with_errors">
    <p>Email:</p>
    <%= f.text_field :email %>
  </div>

  <div class="field_with_errors">
    <p>Password:</p>
    <%= f.password_field :password %>
  </div>

  <div class="field_with_errors">
    <p>Password Confirmation:</p>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h2>My Recipies</h2>

<ul>
  <% @user.recipes.each do |recipe| %>
    <li><%= link_to "#{recipe.name}", recipe_path(recipe) %></li>
  <% end %>
</ul>

<br />

<%= link_to "Create a New Recipe", new_recipe_path %>

<br />

<%= link_to "Browse Recipes", meals_path %>

<br />